# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoInspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inspeccion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Macros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('motor', 'Motor'), ('exterior', 'Exterior'), ('interior', 'Interior'), ('parte_baja', 'Parte Baja')], max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
