# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='tipo_servicio',
            field=models.CharField(choices=[('particular', 'Particular'), ('publico', 'P\xfablico'), ('diplomatico', 'Diplom\xe1tico'), ('oficial', 'Oficial'), ('especialRNMA', 'EspecialRNMA')], default='particular', max_length=100),
        ),
    ]
