# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_delantera', models.ImageField(default='default/no-img.jpg', upload_to='uploads/licencia')),
                ('imagen_trasera', models.ImageField(default='default/no-img.jpg', upload_to='uploads/licencia')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_propietario', models.CharField(choices=[('personal', 'Personal'), ('empresarial', 'Empresarial')], default='personal', max_length=100)),
                ('tipo_documento', models.CharField(blank=True, choices=[('documento_nacional', 'C\xe9dula de ciudadan\xeda'), ('documento_extranjero', 'C\xe9dula de extranjer\xeda'), ('pasaporte', 'Pasaporte')], max_length=100, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('edad', models.CharField(blank=True, max_length=3, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('profesion', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='PropietarioVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pintura', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('numero_chasis', models.CharField(max_length=100)),
                ('numero_motor', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=50)),
                ('rombo', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Color')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietario.Propietario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='licencia',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietario.Propietario'),
        ),
    ]
