# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('documento_nacional', 'C\xe9dula de ciudadan\xeda'), ('documento_extranjero', 'C\xe9dula de extranjer\xeda'), ('pasaporte', 'Pasaporte'), ('nit', 'NIT'), ('nin', 'NIN'), ('tarjeta_identidad', 'Tarjeta de identidad'), ('registro_civil', 'Registro civil'), ('carnet_diplomatico', 'Carnet diplomatico'), ('ti2', 'TI2')], max_length=100, null=True),
        ),
    ]
