# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NacionalidadVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCarroceria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='carroceria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.TipoCarroceria'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.ClaseVehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.NacionalidadVehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.TipoCombustible'),
        ),
    ]
